# Site settings
title: Nathan Eanes, Web Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nathan Eanes is a web designer and developer extrordinaire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathaneanes.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
