# Site settings
title: Nathan Eanes, Web Developer
description: > # this means to ignore newlines until "baseurl:"
  Nathan Eanes is a web designer and developer extrordinaire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathaneanes.com" # the base hostname & protocol for your site
twitter_username: nathaneanes
github_username:  nathaneanes

# Build settings
markdown: kramdown
